### ISSUE TITLE
[Bug]: Change store / locale

### ISSUE THREAD

**Issue by sequensucks** [vuestorefront/magento2#378] opened 2021-12-28 09:42 UTC
### Actual Behavior
When i change a store / locale from a language switcher it works good.
But when i change a store / locale in the url it changes after a second reload page and doesn't logout and clear cart.

### What version of Magento 2 integration are you using?
2.4.3

### What version of Node.js are you using?
v16.12.0

### What browser (and version) are you using?
Chrome Version 96.0.4664.93 (Official Build) (x86_64)

### What operating system (and version) are you using?
macOS Version 12.0.1 (21A559)

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment] 2021-12-28 16:50
@sequensucks can you provide a way to reproduce the process of changing the store via URL :)

I've implemented the store change via the component, so the URL is something that I need to investigate :)

**Comment by sequensucks** [comment] 2021-12-28 18:14
if u add strategy: 'prefix' in the nuxt.config.js in the i18n prop ( https://i18n.nuxtjs.org/strategies/ ) you will get a locale prefix in the url. Like, https://[domain]/en-US
and subsequently you can change store via URL.

**Comment by serge-kaimin** [comment] 2022-01-01 20:42
Is anyone can explain why template's locale prefix is set as 'en-US/', 'de-DE/', if mentioned link on i18n strategies and both magento 1/2 implemented locale prefixes as en/, de/, fr/, etc.?

**Comment by Frodigo** [comment] 2022-01-04 15:05
@serge-kaimin prefixes are configured in `next.config.js` and they correspond to Magento stores configurations.

So in our Magento instance, there is a store view with code `de_DE` so the prefix must be the same because it's used in communication between Magento and VSF.

When you change store code in Magento to `de`, you can change config in `nuxt.config.js` then.

**Comment by Frodigo** [comment] 2022-01-04 15:21
I found another bug:

when you change the store, vsf-currency and vsf-locale cookies are changing to `EUR` and after a few seconds, they are changing to USD and en-US.

Screen recording for reference. 

https://user-images.githubusercontent.com/11998249/148081535-03a92c5b-936c-4f19-8f4f-3c2edd7b9d5e.mov

**Comment by bloodf** [comment] 2022-01-06 16:49
> I found another bug:
> 
> when you change the store, vsf-currency and vsf-locale cookies are changing to `EUR` and after a few seconds, they are changing to USD and en-US.
> 
> Screen recording for reference.
> 
>  change.store.mov

This is fixed with my PR to core to add the autoChangeCookie option on the nuxt-midleware

**Closed** 2022-01-18 15:31 UTC
Labels: bug, vsf_team
